apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-sno-5.vran.ibm.com
  namespace: openshift-gitops
spec: 
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/sno-5.vran.ibm.com/ztp/siteconfig
    repoURL: https://github.com/traghave123/telco-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true