---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-bastion-ca
  namespace: openshift-config
data:
  domain.crt: |

    -----BEGIN CERTIFICATE-----
    MIIDszCCApugAwIBAgIUTncietIN/VeycMuKTImNRs7s/BQwDQYJKoZIhvcNAQEL
    BQAwaTELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQswCQYDVQQHDAJTWjENMAsG
    A1UECgwESUJNLjExMC8GA1UEAwwobWlycm9yLXJlZy00NjEuZnlyZS5pYm0uY29t
    LmZ5cmUuaWJtLmNvbTAeFw0yMjAxMDQwNTQxMjZaFw0zMjAxMDIwNTQxMjZaMGkx
    CzAJBgNVBAYTAklOMQswCQYDVQQIDAJLQTELMAkGA1UEBwwCU1oxDTALBgNVBAoM
    BElCTS4xMTAvBgNVBAMMKG1pcnJvci1yZWctNDYxLmZ5cmUuaWJtLmNvbS5meXJl
    LmlibS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDxo4xrn4T
    JFAA2fslQLwmr+HAwKUI8ukknVRbpdDHUymXyKeACWEXZPxNM5YYQyEk42KZdhJi
    /+T8LmjIoXVJwbwfYQM9D+7clEjGx+RLNd9olZ5oNQViqhnEr++/zFBQIeels5D6
    9HuFxPbQ0dhnGzu0aYFFYhifFY9gQdALNTR/zuy8RMJZLkCAj8+67g2EZccRNnTF
    GHyfvr/DQRwe0eUA5oHRxV4ykY9PuszSScoYSj//9SDJLn7e5im0bPTD0BiHXQKf
    MlMvqa6JVe+ITFnVjFr5L74JivKn45RYyj/+SDC4rH6crI2TUpx4vtznt5qEp//+
    aBZ2vd1djeiJAgMBAAGjUzBRMB0GA1UdDgQWBBSErgCdEDuERJJtEfNoN54laLEH
    zzAfBgNVHSMEGDAWgBSErgCdEDuERJJtEfNoN54laLEHzzAPBgNVHRMBAf8EBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQC6huFUxfjqZEx7lPHhwL/0N4ESK+TZ281V
    pmHPoQzbKTq7G3CixXKksN752XUnFaF+CcpOkBSKsP1geIzuPCWjxfgMIWHYBY0C
    +iN4/BIxzzo7+hZQcJqHLOMq6wWMhQMEWKU4iJ/aHYKnwAlqpvT78d3F3SWhn3a5
    URCl+i7Naky13zpm9xL/MJ6TPWH1RJ2ieb5xtNvlBWgDFT9vlG7rwHZDOGGqKgq3
    ceHdzGddI5l1goYWfdKp5dY8EqxgEZY/W8qVvILGZ5Ao88uwF4W8zfHvq82UNzqV
    c1uqbu4fzArRhpujbNZjZzqyo1kaxGJLABGMWt+oVUyNSyophHO2
    -----END CERTIFICATE-----
