---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJtaXJyb3ItcmVnLTQ2MS5meXJlLmlibS5jb206NTAwMCI6eyJ1c2VybmFtZSI6ImlibXVzZXIiLCJwYXNzd29yZCI6ImlibXBhc3N3b3JkIiwiZW1haWwiOiJwbWFsbGFuYUBpbi5pYm0uY29tIiwiYXV0aCI6ImFXSnRkWE5sY2pwcFltMXdZWE56ZDI5eVpBPT0ifX19Cg==
kind: Secret
metadata:
  name: registry-bastion-ps
  namespace: cnf
type: kubernetes.io/dockerconfigjson
---
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
spec: 
  additionalTrustedCA:
    name: registry-bastion-ca
  registrySources:
    insecureRegistries:
    - mirror-reg-461.fyre.ibm.com:5000
#status:
#  internalRegistryHostname: image-registry.openshift-image-registry.svc:5000
