---
###############################################################################
# O-RAN Midhaul - VF type netdevice
###############################################################################
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: oran-smo-netdevice
  namespace: openshift-sriov-network-operator
spec:
  resourceName: oran_smo_netdevice
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/oran-smo-netdevice: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 6
  nicSelector:
    vendor: "8086"
    deviceID: "158b"
    pfNames:
      - ens1f0#0-3