---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/oss-bss: telco-gitops

bases:
  # Configure chrony
  # - ../../base/configs/chrony
  # Identity Provider (htpasswd)
  # - ../../base/configs/idp-htpasswd
  # local storage operator
  - ../../base/operators/local-storage-operator
  # LSO auto-discovery label
  - ../../base/configs/lso
  # Telco Optimizations
  - ../../base/configs/telco-optimized
  # OpenShift ServiceMesh
  - ../../base/operators/openshift-service-mesh
  # PAO
  # - ../../base/operators/openshift-performance-addon-operator
