apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: r13dell6.vran.ibm.com-gitops
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
#    namespace: test-sno-siteconfig
  project: default
  source:
    path: clusters/r13dell6.vran.ibm.com/ztp/gitops
    repoURL: https://github.com/traghave123/telco-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true