
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: storagecluster-wait-cu-devanahalli60-storage
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/mcp
              echo ""
              echo -n "Waiting for the storage cluster to be ready."
              sleep $SLEEP
              until oc wait --for=condition=available storagecluster ocs-external-storagecluster -n openshift-storage --timeout=60s
              do
                echo -n "...still waiting for the storage cluster to be ready"
                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: storagecluster-wait-job
          env:
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30