---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/combined-ran: telco-gitops

bases:
  # Configure chrony
  # - ../../base/configs/chrony
  # Identity Provider (htpasswd)
  # - ../../base/configs/idp-htpasswd
  # local storage operator
  - ../../base/operators/local-storage-operator
  # LSO auto-discovery label
  - ../../base/configs/lso
  # RWN
  - ../../base/configs/telco-optimized
  # Enable SCTP
  - ../../base/configs/sctp
  # SRIOV
  - ../../base/operators/openshift-sriov-network-operator
  # PAO
  - ../../base/operators/openshift-performance-addon-operator
  # PTP
  - ../../base/operators/openshift-ptp
  # Intel vRAN Acceleration Operators
  - ../../base/operators/vran-acceleration-operators

resources:
  # - 02-mcp-ran-cu.yaml
  # - 02-mcp-ran-du.yaml
  - 50-ran-du-disable-chronyd.yaml
  # # TODO: replace by ks8 job
  # - 01-mcp.yaml

# patches:
# # TODO: replace by k8s job
# - 01-patch-mcp-master.yaml
