---
apiVersion: performance.openshift.io/v1
kind: PerformanceProfile
metadata:
  name: ran-cu-devanahalli60-server-profile-cu-dell-r640-00-pao-profile-cu-dell-r640-00
spec:
  cpu:
    isolated: "4-38,5-39"
    reserved: "0-2,1-3"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 100
      node: 0 
    - size: "1G"
      count: 100
      node: 1 
  numa:
    topologyPolicy: restricted
  nodeSelector:
    node-role.kubernetes.io/ran-cu-devanahalli60-server-profile-cu-dell-r640-00: ""