---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-devanahalli60

commonAnnotations:  
#  argocd.argoproj.io/sync-wave: "10"
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  


resources:
  - 03-label-worker2.mdnhost1.cp.fyre.ibm.com-job.yaml
  - 03-label-worker1.mdnhost1.cp.fyre.ibm.com-job.yaml
  - 03-label-worker0.mdnhost1.cp.fyre.ibm.com-job.yaml
  - 01-cli-job-sa-role.yaml
  - 02-cli-job-sa-rolebinding.yaml