 
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: devanahalli60-sriov-vfio-dell00-server-profile-cu-dell-r640-00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_netdevice"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/devanahalli60-sriov-netdevice-server-profile-cu-dell-r640-00: ""
  deviceType: netdevice
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
          - ens2f1#0-7
    
---
###############################################################################
# specific resourceName for it (eg. sriov-netdevice-smci00)
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: devanahalli60-sriov-a-vfio-dell00-server-profile-cu-dell-r640-00
  namespace: openshift-sriov-network-operator
spec:
  resourceName: "vran_vfio"
  nodeSelector:
    ran.openshift.io/sriov: ""
    ran.openshift.io/devanahalli60-sriov-vfio-server-profile-cu-dell-r640-00: ""
  deviceType: vfio-pci
  priority: 10
  #mtu: 1500
  numVfs: 64
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
          - ens2f1#8-15
    
