---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-nmstate-namespace.yaml
  - 02-nmstate-operatorgroup.yaml
  - 03-nmstate-subscription.yaml
  - 04-nmstate-instance.yaml
