---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
#    argocd.argoproj.io/sync-wave: "30"
  name: label-sno-5-job
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/node
              echo ""
              echo -n "Add node labels"
              until oc wait --selector=node-role.kubernetes.io/ran-cu-devanahalli60-dell00='',kubernetes.io/hostname=sno-5 --for=condition=ready nodes
              do
                echo -n "...still waiting for applying labels"
                oc label node sno-5 ran.openshift.io/devanahalli60-local-storage-dell00=""
                oc label node sno-5 node-role.kubernetes.io/ran-cu-devanahalli60-dell00=""
                oc label node sno-5 ran.openshift.io/ocpvirt=""
                oc label node sno-5 ran.openshift.io/sriov=""
                oc label node sno-5 feature.node.kubernetes.io/network-sriov.capable=true
                oc label node sno-5 ran.openshift.io/devanahalli60-sriov-netdevice-dell00=""
                oc label node sno-5 ran.openshift.io/devanahalli60-sriov-vfio-dell00=""

                sleep $SLEEP
              done
              echo "DONE"
          imagePullPolicy: Always
          name: nodes-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30