---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: label-wait-job-devanahalli60-integrateceph
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/mcp
              echo ""
              echo -n "Waiting for the node to converge."
              sleep $SLEEP
              until oc wait --selector=cluster.ocs.openshift.io/openshift-storage='' --for=condition=ready nodes
              do
                echo -n "...still waiting for node to be labelled"
                sleep $SLEEP
              done
              echo "DONE"
              
          imagePullPolicy: Always
          name: nodes-wait-job
          env:
          - name: SLEEP
            value: "5"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30