---
# To manually create this file from pull-secret.json
# oc create secret generic assisted-deployment-pull-secret -n assisted-installer --from-file=.dockerconfigjson=pull-secret.json --type=kubernetes.io/dockerconfigjson
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: assisted-installer
stringData:
  .dockerconfigjson: 'base64-pull-secret-json-here' << # UPDATE THIS
  type: kubernetes.io/dockerconfigjson
