---
apiVersion: v1
data:
  password: Z2hwX280WFROWEtmRlNLUzI0NG1ONlJBaHpSamJtQm1weDNaSzM1Yw==
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL3RyYWdoYXZlMTIzL3RlbGNvLWdpdG9wcy5naXQ=
  username: dHJhZ2hhdmUxMjM=
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-traghave123-telco-gitops
  namespace: sno-5
type: Opaque